plugins:
  uses:
    - plugin: http://localhost:4004
      runsOn: [ "issue_comment.created" ]
      with:
        # Define configurable items here and the kernel will pass these to the plugin.
        configurableResponse: "Hello, is it me you are looking for?"
        customStringsUrl: "https://raw.githubusercontent.com/ubiquibot/plugin-template/development/strings.json"
  uses:
    - plugin: http://localhost:4001
      runsOn: [ "issues.labeled", "issues.unlabeled" ]
      with:
        labels:
          time:
            - name: "Time: <1 Hour"
              collaboratorOnly: false
            - name: "Time: <2 Hours"
              collaboratorOnly: false
            - name: "Time: <4 Hours"
              collaboratorOnly: false
            - name: "Time: <1 Day"
              collaboratorOnly: false
            - name: "Time: <1 Week"
              collaboratorOnly: false
          priority:
            - name: "Priority: 1 (Normal)"
              collaboratorOnly: false
            - name: "Priority: 2 (Medium)"
              collaboratorOnly: true
            - name: "Priority: 3 (High)"
              collaboratorOnly: false
            - name: "Priority: 4 (Urgent)"
              collaboratorOnly: false
            - name: "Priority: 5 (Emergency)"
              collaboratorOnly: false
        basePriceMultiplier: 1
        publicAccessControl:
          setLabel: true
          fundExternalClosedIssue: false
        globalConfigUpdate:
          excludeRepos: ["devpool-directory", "devpool-directory-private"]

